### ISSUE TITLE
public macros depend on private macros

### ISSUE THREAD

**Issue by asomers** [DonaldWhyte/double#19]
The public `mock_trait!` macro (and probably others too) depends  on the private `__private_mock_trait_new_impl` and `__private_mock_trait_default_impl` macros.  That wasn't a problem in Rust 2015 when macros are imported all or nothing.  But it is a problem in Rust 2018 where macros are imported like any other symbol.  Those private macros should either be public and documented, or else truly private.

**Comment by DonaldWhyte** [comment]
Ack.

**Comment by DonaldWhyte** [comment]
I fixed this issue as part of this PR: https://github.com/DonaldWhyte/double/pull/22.

Note that the fix involved adding the `$crate::` prefix where the "private" macros are used. This means end users no longer need to explicitly import the private module when importing the macros in the Rust 2018 way. For example, this is now possible:

```
extern crate double;

use double::mock_method;
use double::mock_trait;

trait Calculator: Clone {
    fn multiply(&self, x: i32, y: i32) -> i32;
}

mock_trait!(
    MockCalculator,
    multiply(i32, i32) -> i32);
impl Calculator for MockCalculator {
    mock_method!(multiply(&self, x: i32, y: i32) -> i32);
}
```

One unfortunate aspect of this is that, as far as I know, the `__private` macros in macros.rs still need to be made public using `[macro_export]`. It is not possible for the private macros to be "truly" private. I could be wrong about this though. If you believe otherwise, let me know. I'm happy to add another change in to make them truly private.

**Comment by DonaldWhyte** [comment]
The fix for this has been published to crates.io as part of version 0.2.4 of the double crate. Also note that going forward, the git sha of all crate versions will be marked using git tags.
